##########################################
#
# airspy_autocorr.yaml
#
# A quick-and-dirty config to demonstrate the use of the AirSpy
# producer. It gathers data around 1420MHz, channelizes and
# autocorrelates it, then streams to a local listener.
#
# Author: Keith Vanderlinde
#
##########################################
---
type: config
# Logging level can be one of:
# OFF, ERROR, WARN, INFO, DEBUG, DEBUG2 (case insensitive)
# Note DEBUG and DEBUG2 require a build with (-DCMAKE_BUILD_TYPE=Debug)
log_level: info

instrument_name: airspy

samples_per_data_set: 32768 #131072
#samples_per_data_set: 1048576
bytes_per_sample: 2
buffer_depth: 10
cpu_affinity: [4,5,6,7]
num_elements: 2
one: 1
two: 2
sizeof_float: 4

meta_pool:
  kotekan_metadata_pool: chimeMetadata
  num_metadata_objects: 5 * buffer_depth

input_bufA:
  kotekan_buffer: standard
  metadata_pool: meta_pool
  num_frames: buffer_depth
  frame_size: samples_per_data_set * bytes_per_sample

input_bufB:
  kotekan_buffer: standard
  metadata_pool: meta_pool
  num_frames: buffer_depth
  frame_size: samples_per_data_set * bytes_per_sample

sample_bw: 10. #MHz, must be float?
freq: 1422.    #MHz
gain_lna: 4 #0-14
gain_mix: 5 #0-15
gain_if:  5 #0-15
biast_power: false
autostart: true
airspy_inputA:
  kotekan_stage: airspyInput
  out_buf: input_bufA
  serial: 0x03A464C834658167
#  serial: 0x466C64C8335838C7

airspy_inputB:
  kotekan_stage: airspyInput
  out_buf: input_bufB
  serial: 0x440464C8394C614F
#  serial: 0x744C60C821458E4F

lag_align:
  kotekan_stage: AirspyAlign
  in_bufA: input_bufA
  in_bufB: input_bufB
  lag_window: 1048576

spectrum_length: 1024
post_fengine_bufA:
  kotekan_buffer: standard
  metadata_pool: meta_pool
  num_frames: buffer_depth
  frame_size: samples_per_data_set * sizeof_float # * 2 for complex / 2 for real->imag fft
post_fengine_bufB:
  kotekan_buffer: standard
  metadata_pool: meta_pool
  num_frames: buffer_depth
  frame_size: samples_per_data_set * sizeof_float # * 2 for complex / 2 for real->imag fft

spectrum_output:
  fengineA:
    kotekan_stage: fftwEngine
    in_buf: input_bufA
    out_buf: post_fengine_bufA

  fengineB:
    kotekan_stage: fftwEngine
    in_buf: input_bufB
    out_buf: post_fengine_bufB

integration_length: 1024
correlation_output:
  post_corr_buf:
    kotekan_buffer: standard
    metadata_pool: meta_pool
    num_frames: buffer_depth
    frame_size: ( spectrum_length * 4 + one ) * sizeof_float

  xengine:
    kotekan_stage: SimpleCrosscorr
    in_bufA: post_fengine_bufA
    in_bufB: post_fengine_bufB
    out_buf: post_corr_buf

  power_stream:
    kotekan_stage: networkPowerStream
    num_elements: 4
    num_freq: spectrum_length
    destination_port: 23401
    destination_ip: "127.0.0.1"
    destination_protocol: TCP
    in_buf: post_corr_buf

  spawn_pyviewer:
    kotekan_stage: SpawnProcess
    in_buf: post_corr_buf
    exec: "../../python/scripts/js_viewer/livebeam_crosscorr_server.py"