##########################################
#
# chime_psr.yaml
#
# CHIME config to capture VDIF frames from CHIME/pulsar,
# assemble them into frames, and stripe those frames to drivesets.
#
# Author: Keith Vanderlinde
#
##########################################
---
type: config
# Logging level can be one of:
# OFF, ERROR, WARN, INFO, DEBUG, DEBUG2 (case insensitive)
# Note DEBUG and DEBUG2 require a build with (-DCMAKE_BUILD_TYPE=Debug)
log_level: warn

num_vdif_threads: 256
timesamples_per_frame: 3125

buffer_depth: 128
cpu_affinity: [0,1,2,3,4,5,6,7,8,9,10,11]
sizeof_float: 4
sizeof_short: 2

#N2 stuff
block_size: 32

# Pool
main_pool:
    kotekan_metadata_pool: chimeMetadata
    num_metadata_objects: 15 * buffer_depth

recv_depth: 64

pulsar_input_buffers:
    num_frames: buffer_depth
    num_frames: buffer_depth
    vdif_packet_size: 5032
    num_vdif_frames: 5
    frame_size: vdif_packet_size * num_vdif_threads * num_vdif_frames
    metadata_pool: main_pool
    pulsar_input_buffer:
        kotekan_buffer: standard

pulsar_receive:
  port: 1414
  log_level: info
  cpu_affinity: [11]
  kotekan_process: psrRecv
  out_buf: pulsar_input_buffer

raw_capture:
   kotekan_process: nDiskFileWrite
#################################
# THIS IS THE PLACE TO EDIT!!!  #
#################################
   note: CHIMEpulsar test run
   instrument_name: chime_psr
#Change this if you want to record
   write_to_disk: true
   gain_files: []
   num_elements: 2
#   samples_per_data_set: 6250
   num_disks: 10
   disk_base: /drives/
   disk_set: G
   in_buf: pulsar_input_buffer
