---
type: config
# Logging level can be one of:
# OFF, ERROR, WARN, INFO, DEBUG, DEBUG2 (case insensitive)
# Note DEBUG and DEBUG2 require a build with (-DCMAKE_BUILD_TYPE=Debug)
log_level: debug

# Default buffer depth (number of frames in buffer)
buffer_depth: 8

# Default core assignments
cpu_affinity: [8,9,10,11,13,14,15]

packets_per_frame: 32768 * 4
# Set this to the size of the packet plus Ethernet/IP/UDP headers
packet_size: 8224
max_rx_pkt_len: 9000


network_capture_buf_2:
  kotekan_buffer: standard
  num_frames: buffer_depth
  frame_size: packets_per_frame * packet_size / 4
  numa_node: 0
network_capture_buf_3:
  kotekan_buffer: standard
  num_frames: buffer_depth
  frame_size: packets_per_frame * packet_size / 4
  numa_node: 0


buffer_recv_0:
    kotekan_stage: bufferRecv
    log_level: warn
    buf: network_capture_buf_2
    listen_port: 11027
    num_threads: 1

buffer_recv_0:
    kotekan_stage: bufferRecv
    log_level: warn
    buf: network_capture_buf_3
    listen_port: 11028
    num_threads: 1
