---
type: config
# Logging level can be one of:
# OFF, ERROR, WARN, INFO, DEBUG, DEBUG2 (case insensitive)
# Note DEBUG and DEBUG2 require a build with (-DCMAKE_BUILD_TYPE=Debug)
log_level: debug

buffer_depth: 8
samples_per_data_set: 49152
num_elements: 16
num_local_freq: 128

cpu_affinity: [8, 72, 9, 73, 10, 74, 11, 75]

# Pool
main_pool:
    kotekan_metadata_pool: chimeMetadata
    num_metadata_objects: 128 * buffer_depth

# Buffers
gpu_input_buffers:
    num_frames: buffer_depth
    frame_size: samples_per_data_set * num_elements * num_local_freq
    metadata_pool: main_pool
    gpu_input_buffer_0:
        kotekan_buffer: standard
    gpu_input_buffer_1:
        kotekan_buffer: standard
    gpu_input_buffer_2:
        kotekan_buffer: standard
    gpu_input_buffer_3:
        kotekan_buffer: standard
    gpu_input_buffer_4:
        kotekan_buffer: standard
    gpu_input_buffer_5:
        kotekan_buffer: standard
    gpu_input_buffer_6:
        kotekan_buffer: standard
    gpu_input_buffer_7:
        kotekan_buffer: standard
    gpu_input_buffer_8:
        kotekan_buffer: standard
    gpu_input_buffer_9:
        kotekan_buffer: standard
    gpu_input_buffer_10:
        kotekan_buffer: standard
    gpu_input_buffer_11:
        kotekan_buffer: standard
    gpu_input_buffer_12:
        kotekan_buffer: standard
    gpu_input_buffer_13:
        kotekan_buffer: standard
    gpu_input_buffer_14:
        kotekan_buffer: standard
    gpu_input_buffer_15:
        kotekan_buffer: standard
    gpu_input_buffer_16:
        kotekan_buffer: standard
    gpu_input_buffer_17:
        kotekan_buffer: standard
    gpu_input_buffer_18:
        kotekan_buffer: standard
    gpu_input_buffer_19:
        kotekan_buffer: standard
    gpu_input_buffer_20:
        kotekan_buffer: standard
    gpu_input_buffer_21:
        kotekan_buffer: standard
    gpu_input_buffer_22:
        kotekan_buffer: standard
    gpu_input_buffer_23:
        kotekan_buffer: standard


lost_samples_buffers:
    num_frames: buffer_depth
    frame_size: samples_per_data_set
    metadata_pool: main_pool
    lost_samples_buffer_0:
        kotekan_buffer: standard
    lost_samples_buffer_1:
        kotekan_buffer: standard
    lost_samples_buffer_2:
        kotekan_buffer: standard
    lost_samples_buffer_3:
        kotekan_buffer: standard
    lost_samples_buffer_4:
        kotekan_buffer: standard
    lost_samples_buffer_5:
        kotekan_buffer: standard
    lost_samples_buffer_6:
        kotekan_buffer: standard
    lost_samples_buffer_7:
        kotekan_buffer: standard
    lost_samples_buffer_8:
        kotekan_buffer: standard
    lost_samples_buffer_9:
        kotekan_buffer: standard
    lost_samples_buffer_10:
        kotekan_buffer: standard
    lost_samples_buffer_11:
        kotekan_buffer: standard
    lost_samples_buffer_12:
        kotekan_buffer: standard
    lost_samples_buffer_13:
        kotekan_buffer: standard
    lost_samples_buffer_14:
        kotekan_buffer: standard
    lost_samples_buffer_15:
        kotekan_buffer: standard
    lost_samples_buffer_16:
        kotekan_buffer: standard
    lost_samples_buffer_17:
        kotekan_buffer: standard
    lost_samples_buffer_18:
        kotekan_buffer: standard
    lost_samples_buffer_19:
        kotekan_buffer: standard
    lost_samples_buffer_20:
        kotekan_buffer: standard
    lost_samples_buffer_21:
        kotekan_buffer: standard
    lost_samples_buffer_22:
        kotekan_buffer: standard
    lost_samples_buffer_23:
        kotekan_buffer: standard


dpdk:
    kotekan_stage: dpdkCore
    # Format is index = lcore, value = cpu core
    lcore_cpu_map: [0,64,1,65,2,66,3,67,4,68,5,69]
    master_lcore_cpu: 6
    fpga_packet_size: 4680
    alignment: samples_per_data_set
    mbuf_cache_size: 250
    # Format is index = lcore, value = array of port IDs
    # so [[0,1],[2,3]] maps lcore 0 to service ports 0 and 1,
    # and lcore 1 to service ports 2 and 3.
    lcore_port_map:
        - [0,1]
        - [2,3]
        - [4,5]
        - [6,7]
        - [8,9]
        - [10,11]
        - [12,13]
        - [14,15]
        - [16,17]
        - [18,19]
        - [20,21]
        - [22,23]

    # One handler must be given per port on the system.
    handlers:
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_0
          lost_samples_buf: lost_samples_buffer_0
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_1
          lost_samples_buf: lost_samples_buffer_1
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_2
          lost_samples_buf: lost_samples_buffer_2
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_3
          lost_samples_buf: lost_samples_buffer_3
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_4
          lost_samples_buf: lost_samples_buffer_4
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_5
          lost_samples_buf: lost_samples_buffer_5
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_6
          lost_samples_buf: lost_samples_buffer_6
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_7
          lost_samples_buf: lost_samples_buffer_7
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_8
          lost_samples_buf: lost_samples_buffer_8
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_9
          lost_samples_buf: lost_samples_buffer_9
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_10
          lost_samples_buf: lost_samples_buffer_10
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_11
          lost_samples_buf: lost_samples_buffer_11
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_12
          lost_samples_buf: lost_samples_buffer_12
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_13
          lost_samples_buf: lost_samples_buffer_13
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_14
          lost_samples_buf: lost_samples_buffer_14
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_15
          lost_samples_buf: lost_samples_buffer_15
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_16
          lost_samples_buf: lost_samples_buffer_16
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_17
          lost_samples_buf: lost_samples_buffer_17
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_18
          lost_samples_buf: lost_samples_buffer_18
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_19
          lost_samples_buf: lost_samples_buffer_19
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_20
          lost_samples_buf: lost_samples_buffer_20
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_21
          lost_samples_buf: lost_samples_buffer_21
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_22
          lost_samples_buf: lost_samples_buffer_22
        - dpdk_handler: iceBoardStandard
          out_buf: gpu_input_buffer_23
          lost_samples_buf: lost_samples_buffer_23


zero_samples:
    zero_0:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_0
        lost_samples_buf: lost_samples_buffer_0
    zero_1:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_1
        lost_samples_buf: lost_samples_buffer_1
    zero_2:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_2
        lost_samples_buf: lost_samples_buffer_2
    zero_3:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_3
        lost_samples_buf: lost_samples_buffer_3
    zero_4:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_4
        lost_samples_buf: lost_samples_buffer_4
    zero_5:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_5
        lost_samples_buf: lost_samples_buffer_5
    zero_6:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_6
        lost_samples_buf: lost_samples_buffer_6
    zero_7:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_7
        lost_samples_buf: lost_samples_buffer_7
    zero_8:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_8
        lost_samples_buf: lost_samples_buffer_8
    zero_9:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_9
        lost_samples_buf: lost_samples_buffer_9
    zero_10:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_10
        lost_samples_buf: lost_samples_buffer_10
    zero_11:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_11
        lost_samples_buf: lost_samples_buffer_11
    zero_12:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_12
        lost_samples_buf: lost_samples_buffer_12
    zero_13:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_13
        lost_samples_buf: lost_samples_buffer_13
    zero_14:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_14
        lost_samples_buf: lost_samples_buffer_14
    zero_15:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_15
        lost_samples_buf: lost_samples_buffer_15
    zero_16:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_16
        lost_samples_buf: lost_samples_buffer_16
    zero_17:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_17
        lost_samples_buf: lost_samples_buffer_17
    zero_18:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_18
        lost_samples_buf: lost_samples_buffer_18
    zero_19:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_19
        lost_samples_buf: lost_samples_buffer_19
    zero_20:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_20
        lost_samples_buf: lost_samples_buffer_20
    zero_21:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_21
        lost_samples_buf: lost_samples_buffer_21
    zero_22:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_22
        lost_samples_buf: lost_samples_buffer_22
    zero_23:
        kotekan_stage: zeroSamples
        out_buf: gpu_input_buffer_23
        lost_samples_buf: lost_samples_buffer_23

