---
type: config
# Logging level can be one of:
# OFF, ERROR, WARN, INFO, DEBUG, DEBUG2 (case insensitive)
# Note DEBUG and DEBUG2 require a build with (-DCMAKE_BUILD_TYPE=Debug)
log_level: DEBUG

instrument_name: pathfinder

num_elements: 256
num_adjusted_elements: 256
num_local_freq: 8
num_adjusted_local_freq: 8
num_total_freq: 64
#num_adjusted_elements/block_size * (num_adjusted_elements/block_size + 1)/2; block_size = 32.
num_blocks: 36
block_size: 32
samples_per_data_set: 32768
num_data_sets: 1
buffer_depth: 6
num_gpu_frames: 256
num_links: 8
link_map: [0,0,1,1,1,2,2,2]
num_gpus: 3
cpu_affinity: [4,5,6,7]
enable_gating: false
sizeof_cl_int: 4
sizeof_tcp_frame_header: 116
sizeof_complex_int_t: 8
sizeof_per_frequency_data: 16
sizeof_per_element_data: 12
sizeof_uint8_t: 1
sizeof_gate_frame_header: 236
sizeof_float: 4

num_links_fury: 8
num_links_270: 2
num_links_280: 3

num_links_per_gpu: 4

#RFI stuff
sk_step: 4096
rfi_combined: True
frames_per_packet: 1


# Keeping and eye on status
buffer_status:
  kotekan_process: bufferStatus
  time_delay: 5000000 #microsec

# Pool
main_pool:
    kotekan_metadata_pool: chimeMetadata
    num_metadata_objects: 10 * buffer_depth * num_links

gpu_input_buffers:
    frame_size: samples_per_data_set * num_elements * num_local_freq * num_data_sets
    metadata_pool: main_pool
    gpu_280_input_buffer_0:
        kotekan_buffer: standard
        num_frames: buffer_depth * num_links_280
    gpu_280_input_buffer_1:
        kotekan_buffer: standard
        num_frames: buffer_depth * num_links_280
    gpu_270_input_buffer_0:
        kotekan_buffer: standard
        num_frames: buffer_depth * num_links_270

gpu_output_buffers:
    frame_size: num_local_freq * num_blocks * (block_size*block_size)*2.*num_data_sets  * sizeof_cl_int
    metadata_pool: main_pool
    gpu_output_buffer_0:
        kotekan_buffer: standard
        num_frames: buffer_depth * num_links_270
    gpu_output_buffer_1:
        kotekan_buffer: standard
        num_frames: buffer_depth * num_links_280
    gpu_output_buffer_2:
        kotekan_buffer: standard
        num_frames: buffer_depth * num_links_280

gpu_rfi_output_buffers:
    frame_size: num_local_freq * (samples_per_data_set/sk_step) * sizeof_float
    metadata_pool: main_pool
    gpu_rfi_output_buffer_0:
        kotekan_buffer: standard
        num_frames: buffer_depth * num_links_270
    gpu_rfi_output_buffer_1:
        kotekan_buffer: standard
        num_frames: buffer_depth * num_links_280
    gpu_rfi_output_buffer_2:
        kotekan_buffer: standard
        num_frames: buffer_depth * num_links_280


beamform_output_buffers:
    frame_size: samples_per_data_set * num_data_sets * num_local_freq * 2
    metadata_pool: main_pool
    beam_output_buffer_0:
        kotekan_buffer: standard
        num_frames: buffer_depth * num_links_270
    beam_output_buffer_1:
        kotekan_buffer: standard
        num_frames: buffer_depth * num_links_280
    beam_output_buffer_2:
        kotekan_buffer: standard
        num_frames: buffer_depth * num_links_280

#dpdk:
#  kotekan_process: dpdkWrapper
#  mode: no_shuffle
#  num_lcores: 4
#  udp_packet_size: 4800
#  timesamples_per_packet: 2
#  network_out_buf_0: gpu_270_input_buffer_0
#  network_out_buf_1: gpu_280_input_buffer_0
#  network_out_buf_2: gpu_280_input_buffer_1

gen_data:
  type: const
  value: 153
  test_data_gen_0:
    kotekan_process: testDataGen
    network_out_buf: gpu_270_input_buffer_0
  test_data_gen_1:
    kotekan_process: testDataGen
    network_out_buf: gpu_280_input_buffer_0
  test_data_gen_2:
    kotekan_process: testDataGen
    network_out_buf: gpu_280_input_buffer_1

gpu:
  commands:
  - name: input_data_stage
    kernel: ''
#  - name: beamform_phase_data
#    kernel: ''
#  - name: offset_accumulator
#    kernel: "../lib/opencl/kernels/offset_accumulator.cl"
#  - name: preseed_multifreq
#    kernel: "../lib/opencl/kernels/preseed_multifreq.cl"
#  - name: pairwise_correlator
#    kernel: "../lib/opencl/kernels/pairwise_correlator.cl"
#  - name: beamform_kernel
#    kernel: "../lib/opencl/kernels/beamform_tree_scale.cl"
#  - name: output_beamform_result
#    kernel: ''
  - name: clRfiTimeSum
    kernel: "../lib/opencl/kernels/rfi_chime_timesum.cl"
  - name: clRfiInputSum
    kernel: "../lib/opencl/kernels/rfi_chime_inputsum.cl"
  - name: clRfiOutput
    kernel: ''
  - name: output_data_result
    kernel: ''
  ts_element_offset: 0
  ts_num_elem_to_shift: 0
  ts_samples_to_shift: 0
  use_timeshift: 0
  enable_beamforming: false
  instrument_lat: 49.3203
  instrument_long: -119.6175
  ra: 53.5
  dec: 54.6
  element_mask: []
  scale_factor: 1.0
  do_not_track: 1
  fixed_time: 1441828309
  gpu_0:
    kotekan_process: clProcess
    gpu_id: 0
    network_buffer: gpu_270_input_buffer_0
    output_buffer: gpu_output_buffer_0
    beam_out_buf: beam_output_buffer_0
    rfi_out_buf: gpu_rfi_output_buffer_0
  gpu_1:
    kotekan_process: clProcess
    gpu_id: 1
    network_buffer: gpu_280_input_buffer_0
    output_buffer: gpu_output_buffer_1
    beam_out_buf: beam_output_buffer_1
    rfi_out_buf: gpu_rfi_output_buffer_1
  gpu_2:
    kotekan_process: clProcess
    gpu_id: 2
    network_buffer: gpu_280_input_buffer_1
    output_buffer: gpu_output_buffer_2
    beam_out_buf: beam_output_buffer_2
    rfi_out_buf: gpu_rfi_output_buffer_2




