##########################################
#
# synthesis_testing.yaml
#
# A quick-and-dirty config to test de-walshing.
#
# Author: Keith Vanderlinde
#
##########################################
---
type: config
# Logging level can be one of:
# OFF, ERROR, WARN, INFO, DEBUG, DEBUG2 (case insensitive)
# Note DEBUG and DEBUG2 require a build with (-DCMAKE_BUILD_TYPE=Debug)
log_level: info

one: 1
two: 2
sizeof_float: 4
sizeof_int: 4
num_elements: 16

buffer_depth: 10
cpu_affinity: [4,5,6,7]

meta_pool:
  kotekan_metadata_pool: chimeMetadata
  num_metadata_objects: 5 * buffer_depth

input_buf:
  kotekan_buffer: standard
  metadata_pool: meta_pool
  num_frames: buffer_depth
  frame_size: num_elements * num_elements * sizeof_float + sizeof_int

synthesis_dewalsher:
  kotekan_stage: SynthesisDeWalsh
  out_buf: input_buf
  device: '/dev/ttyACM0'