version: '2.3'  # extends function removed in v3
services:
    gpu:
        build: .
        volumes:
            - ./ch_gpu/build/kotekan:/code
        configs:
            - source: ./ch_gpu/kotekan/kotekan_docker_gpu.yaml
              target: /kotekan_config.yaml
        networks:
            - receiver_net
        hostname: cn...  # Does this work?
    receiver:
        build: .
        volumes:
            - ./ch_gpu/build/kotekan:/code
            - ./data:/data
        configs:
            - source: ./ch_gpu/kotekan/kotekan_docker_receiver.yaml
              target: /kotekan_config.yaml
        networks:
            - receiver_net
networks:
    receiver_net:
