version: '2.3'  # extends function removed in v3
services:
    gpu:
        build: .
        volumes:
            - ./ch_gpu:/code
        networks:
            - receiver_net
        hostname: cn...  # Does this work?
        environment:
            KOTEKAN_CONFIG: /code/kotekan/kotekan_docker_gpu.yaml
    receiver:
        build: .
        volumes:
            - ./ch_gpu:/code
            - ./data:/data
        networks:
            - receiver_net
        hostname: recv...
        environment:
            KOTEKAN_CONFIG: /code/kotekan/kotekan_docker_recv.yaml
networks:
    receiver_net:
        driver: bridge
